#ifndef GETFREESPACE_GLOBAL_H
#define GETFREESPACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GETFREESPACE_LIBRARY)
#  define GETFREESPACESHARED_EXPORT Q_DECL_EXPORT
#else
#  define GETFREESPACESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GETFREESPACE_GLOBAL_H
